modLoader="kotlinforforge"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile="icon.png"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="refinedstorage"
type="required"
versionRange="[2.0.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="buildinggadgets2"
type="required"
versionRange="[1.3.9,)"
ordering="AFTER"
side="BOTH"

